Add local network
00labs/huma-js pull request #46
Opened 2023-09-13 10:05 UTC by shan-57blocks

Most important updates of V2 comparing to V1:
1, Generate pool infos from metadata json file by chain
2, Remove POOL_TYPE for v2
3, Abstract common code for hooks like useContractValue

2023-09-13 15:28 UTC, mliu requested changes

2023-09-13 15:28 UTC, mliu commented on packages/huma-shared/src/v2/utils/pool.ts
> +  }
Can we just return undefined here if no chainId is given and enforce the type when we call this funciton?

2023-09-13 15:28 UTC, mliu commented on packages/huma-shared/src/v2/utils/pool.ts
> +export const getChainPoolNamesV2 = (chainId: number | undefined) => {
Can we add type hints for return types?

2023-09-14 06:03 UTC, shan-57blocks commented on packages/huma-shared/src/v2/metadata/Localhost.json
> +      "decimals": 18,
Fetching pool related info from contract was considered, but then it will make the poolInfo async which will complicate the consumers of poolInfo. 
Another idea would be creating a script to generate the pool related info automatically, I think we can improve this later.

2023-09-14 06:13 UTC, shan-57blocks commented on packages/huma-shared/src/v2/metadata/Localhost.json
> +    "pool": "0x1fA02b2d6A771842690194Cf62D91bdd92BfE28d",
Fetching pool related info from contract was considered, but then the poolInfo would be async which will complicate the consumers of poolInfo.
Another idea would be creating a script to generate the pool related info automatically, I think we can improve this later.

2023-09-14 08:15 UTC, shan-57blocks commented on packages/huma-shared/src/v2/metadata/Localhost.json
> +{
Updated.

2023-09-14 08:15 UTC, shan-57blocks commented on packages/huma-shared/src/v2/utils/pool.ts
> +  [chainId: number]: {
Updated

2023-09-14 08:16 UTC, shan-57blocks commented on packages/huma-shared/src/v2/utils/pool.ts
> +  }
Updated

2023-09-14 08:16 UTC, shan-57blocks commented on packages/huma-shared/src/v2/utils/pool.ts
> +export const getChainPoolNamesV2 = (chainId: number | undefined) => {
Updated

2023-09-19 02:27 UTC, mliu requested changes

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/src/v2/hooks/usePool.ts
> +  const { chainId } = useWeb3React()
I prefer we pass in chainId instead of using the web3react hooks, what do you think?

1. Will be easier to migrate to wagmi in the future if we choose to do so
2. huma-shared becomes implementation-agnostic, AKA you can call it from SDK or dapp.

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/src/v2/metadata/Localhost.ts
> +    pool: '0x1fA02b2d6A771842690194Cf62D91bdd92BfE28d',
Do we have deploy scripts on v2 to guarantee the same pool addresses on localhost?

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/tests/v2/utils/poo.test.ts
> +import { ChainEnum } from '../../../src/utils'
you misspelled this filename lol

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/src/v2/index.ts
> +export * from './utils'
Can we configure prettier to also add newlines to huma-shared files?

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/src/v2/utils/pool.ts
> +  Object.keys(poolsInfoV2[chainId]).forEach((poolName) => {
The poolName is enforced as type POOL_NAME, so I think this check is redundant. Can be made cleaner with something like:

poolNames = Object.keys(poolsInfoV2[chain(Id)])

2023-09-19 02:27 UTC, mliu commented on packages/huma-shared/src/v2/utils/pool.ts
> +export const POOLS_INFO_V2 = getPoolsInfoV2()
Why do we have to run this logic every time we fetch poolsInfo vs just having everything already defined in an object like we do now?

2023-09-19 07:02 UTC, shan-57blocks commented on packages/huma-shared/src/v2/hooks/usePool.ts
> +  const { chainId } = useWeb3React()
Good point. Updated.

2023-09-19 07:03 UTC, shan-57blocks commented on packages/huma-shared/src/v2/metadata/Localhost.ts
> +    pool: '0x1fA02b2d6A771842690194Cf62D91bdd92BfE28d',
Actually I have successfully deployed the V2 Contracts to mumbai, so we can delete the localhost config.

2023-09-19 07:03 UTC, shan-57blocks commented on packages/huma-shared/tests/v2/utils/poo.test.ts
> +import { ChainEnum } from '../../../src/utils'
Updated.

2023-09-19 07:03 UTC, shan-57blocks commented on packages/huma-shared/src/v2/index.ts
> +export * from './utils'
I think prettier will add the newline automatically.

2023-09-19 07:03 UTC, shan-57blocks commented on packages/huma-shared/src/v2/utils/pool.ts
> +  Object.keys(poolsInfoV2[chainId]).forEach((poolName) => {
Updated. The first place to add the type guard is to avoid type casting. But I think it's ok to cast here.

2023-09-19 07:04 UTC, shan-57blocks commented on packages/huma-shared/src/v2/utils/pool.ts
> +export const POOLS_INFO_V2 = getPoolsInfoV2()
getPoolsInfoV2 will only be called the first time.

2023-09-20 16:28 UTC, mliu reviewed
My only comment is what's the point of PoolsMetadataV2? Why not define the poolName, poolAbi, and trancheVaultAbi directly in PoolInfoV2?

2023-09-21 01:55 UTC, shan-57blocks commented
> My only comment is what's the point of PoolsMetadataV2? Why not define the poolName, poolAbi, and trancheVaultAbi directly in PoolInfoV2?

At the first place, as the metadata was json file it's impossible to import the abi file. I missed this part when changing metadata from json to ts file. Will update it.

2023-09-21 03:15 UTC, shan-57blocks commented
> > My only comment is what's the point of PoolsMetadataV2? Why not define the poolName, poolAbi, and trancheVaultAbi directly in PoolInfoV2?
> 
> At the first place, as the metadata was json file it's impossible to import the abi file. I missed this part when changing metadata from json to ts file. Will update it.

Updated

2023-09-21 03:24 UTC, mliu approved these changes

2023-09-22 06:21 UTC, merged